name: DigiHealth
description: FIRST Innovation Challenge Submission

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  provider: ^5.0.0
  lists: ^1.0.0
  firebase_auth: ^1.2.0
  cloud_firestore: ^2.2.0
  firebase_analytics: ^8.1.0
  firebase_database: ^7.0.0
  firebase_core: ^1.2.0
  auto_size_text: ^2.1.0
  flutter_spinkit: ^5.0.0
  vertical_card_pager: ^1.5.0
  profanity_filter: ^1.0.4
  giffy_dialog: ^1.8.0
  draw_graph: ^1.0.0
  flutter_launcher_icons: ^0.9.0
  vs_scrollbar: ^0.1.2
  category_picker: ^1.0.1
  date_picker_timeline: ^1.2.3
  grouped_buttons: ^1.0.4
  multi_charts: ^0.2.0
  animated_text_kit: ^4.2.1
  fl_chart: ^0.36.1
  webview_flutter: ^2.0.8
  email_validator: ^2.0.1
  health_kit: ^0.0.3
  conditional_questions: ^2.0.0
  flutter_dropdown_alert: ^1.0.2
  intro_slider: ^2.4.3
  horizontal_card_pager: ^1.1.1
  percent_indicator: ^3.0.1
  keyboard_actions: ^3.4.0
  showcaseview: ^0.1.6
  line_icons: ^2.0.0
  heatmap_calendar: ^1.2.8
  slide_countdown_clock: ^1.0.3
  flip_card: ^0.5.0
  app_tracking_transparency: ^2.0.1
  flutter_chat_ui: ^1.1.3

flutter_icons:
  image_path: "assets/DigiHealthLogo.png"
  image_path_android: "assets/DigiHealthLogoAndroid.png"
  ios: true
  android: true


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-ExtraLight.ttf
        - asset: fonts/Nunito-Light.ttf
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-SemiBold.ttf
        - asset: fonts/Nunito-Bold.ttf
        - asset: fonts/Nunito-ExtraBold.ttf
        - asset: fonts/Nunito-Black.ttf
    - family: Barlow
      fonts:
        - asset: fonts/Barlow-BoldItalic.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - DigiHealthBanner.png
    - images/
    - welcome.gif
    - rank.png
    - DigiHealthLogo.png
    - DigiHealthLogoAndroid.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
